bmc: Add service to disable abr boot watchdog on Goldfinch
Change-Id: Iadae3a8ad9415366d07bcc507301f11f4c49677b

diff --git a/debian/sonic-platform-arista-all.postinst b/debian/sonic-platform-arista-all.postinst
--- a/debian/sonic-platform-arista-all.postinst
+++ b/debian/sonic-platform-arista-all.postinst
@@ -24,6 +24,10 @@ pip3 install --root-user-action=ignore --no-deps "$pywhl"
 
 systemctl daemon-reload
 
+if ! systemctl enable --now platform-arista-disable-boot-watchdog.service; then
+    echo "Warning: failed to start Goldfinch boot-watchdog disarm service" >&2
+fi
+
 svcs="$(grep /lib/systemd/system/platform-arista \
     /var/lib/dpkg/info/sonic-platform-arista-all.list  | sed 's/.*\///')"
 
